# HawkTab AI — master R (deterministic)
# Session: output-2025-08-08T22-06-58-209Z
# Generated: 2025-08-08T22:10:00.927Z

library(haven)
library(jsonlite)
data <- read_sav('temp-outputs/output-2025-08-08T22-06-58-209Z/dataFile.sav')

warnings <- character()

# Cut: Cards
cut_specialty_cards <- tryCatch({ with(data, (S2 == 1 & S2a == 1)) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Cards', ':', e$message)); NULL })
# Cut: PCPs
cut_specialty_pcps <- tryCatch({ with(data, S2 == 2) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'PCPs', ':', e$message)); NULL })
# Cut: Nephs
cut_specialty_nephs <- tryCatch({ with(data, S2 == 3) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Nephs', ':', e$message)); NULL })
# Cut: Endos
cut_specialty_endos <- tryCatch({ with(data, S2 == 4) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Endos', ':', e$message)); NULL })
# Cut: Lipids
cut_specialty_lipids <- tryCatch({ with(data, S2 == 5) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Lipids', ':', e$message)); NULL })
# Cut: HCP
cut_role_hcp <- tryCatch({ with(data, S2b %in% c(1,2,3)) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'HCP', ':', e$message)); NULL })
# Cut: NP/PA
cut_role_np_pa <- tryCatch({ with(data, S2b %in% c(2,3)) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'NP/PA', ':', e$message)); NULL })
# Cut: Higher
cut_volume_of_adult_ascvd_patients_higher <- tryCatch({ with(data, S11 >= median(S11, na.rm = TRUE)) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Higher', ':', e$message)); NULL })
# Cut: Lower
cut_volume_of_adult_ascvd_patients_lower <- tryCatch({ with(data, S11 < median(S11, na.rm = TRUE)) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Lower', ':', e$message)); NULL })
# Cut: Tier 1
cut_tiers_tier_1 <- tryCatch({ with(data, qLIST_TIER == 1) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Tier 1', ':', e$message)); NULL })
# Cut: Tier 2
cut_tiers_tier_2 <- tryCatch({ with(data, qLIST_TIER == 2) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Tier 2', ':', e$message)); NULL })
# Cut: Tier 3
cut_tiers_tier_3 <- tryCatch({ with(data, qLIST_TIER == 3) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Tier 3', ':', e$message)); NULL })
# Cut: Tier 4
cut_tiers_tier_4 <- tryCatch({ with(data, qLIST_TIER == 4) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Tier 4', ':', e$message)); NULL })
# Cut: Segment A
cut_segments_segment_a <- tryCatch({ with(data, Segment == "Segment A") }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Segment A', ':', e$message)); NULL })
# Cut: Segment B
cut_segments_segment_b <- tryCatch({ with(data, Segment == "Segment B") }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Segment B', ':', e$message)); NULL })
# Cut: Segment C
cut_segments_segment_c <- tryCatch({ with(data, Segment == "Segment C") }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Segment C', ':', e$message)); NULL })
# Cut: Segment D
cut_segments_segment_d <- tryCatch({ with(data, Segment == "Segment D") }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Segment D', ':', e$message)); NULL })
# Cut: Priority Account
cut_priority_accounts_priority_account <- tryCatch({ with(data, qLIST_PRIORITY_ACCOUNT == 1) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Priority Account', ':', e$message)); NULL })
# Cut: Non-Priority Account
cut_priority_accounts_non_priority_account <- tryCatch({ with(data, qLIST_PRIORITY_ACCOUNT == 2) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Non-Priority Account', ':', e$message)); NULL })
# Cut: Total
cut_total_total <- tryCatch({ with(data, status == 3) }, error = function(e) { warnings <<- c(warnings, paste0('cut:', 'Total', ':', e$message)); NULL })

cuts <- list()
if (!is.null(cut_specialty_cards) && is.logical(cut_specialty_cards)) { cuts[['Cards']] <- cut_specialty_cards } else { warnings <- c(warnings, paste0('cut_invalid:', 'Cards')) }
if (!is.null(cut_specialty_pcps) && is.logical(cut_specialty_pcps)) { cuts[['PCPs']] <- cut_specialty_pcps } else { warnings <- c(warnings, paste0('cut_invalid:', 'PCPs')) }
if (!is.null(cut_specialty_nephs) && is.logical(cut_specialty_nephs)) { cuts[['Nephs']] <- cut_specialty_nephs } else { warnings <- c(warnings, paste0('cut_invalid:', 'Nephs')) }
if (!is.null(cut_specialty_endos) && is.logical(cut_specialty_endos)) { cuts[['Endos']] <- cut_specialty_endos } else { warnings <- c(warnings, paste0('cut_invalid:', 'Endos')) }
if (!is.null(cut_specialty_lipids) && is.logical(cut_specialty_lipids)) { cuts[['Lipids']] <- cut_specialty_lipids } else { warnings <- c(warnings, paste0('cut_invalid:', 'Lipids')) }
if (!is.null(cut_role_hcp) && is.logical(cut_role_hcp)) { cuts[['HCP']] <- cut_role_hcp } else { warnings <- c(warnings, paste0('cut_invalid:', 'HCP')) }
if (!is.null(cut_role_np_pa) && is.logical(cut_role_np_pa)) { cuts[['NP/PA']] <- cut_role_np_pa } else { warnings <- c(warnings, paste0('cut_invalid:', 'NP/PA')) }
if (!is.null(cut_volume_of_adult_ascvd_patients_higher) && is.logical(cut_volume_of_adult_ascvd_patients_higher)) { cuts[['Higher']] <- cut_volume_of_adult_ascvd_patients_higher } else { warnings <- c(warnings, paste0('cut_invalid:', 'Higher')) }
if (!is.null(cut_volume_of_adult_ascvd_patients_lower) && is.logical(cut_volume_of_adult_ascvd_patients_lower)) { cuts[['Lower']] <- cut_volume_of_adult_ascvd_patients_lower } else { warnings <- c(warnings, paste0('cut_invalid:', 'Lower')) }
if (!is.null(cut_tiers_tier_1) && is.logical(cut_tiers_tier_1)) { cuts[['Tier 1']] <- cut_tiers_tier_1 } else { warnings <- c(warnings, paste0('cut_invalid:', 'Tier 1')) }
if (!is.null(cut_tiers_tier_2) && is.logical(cut_tiers_tier_2)) { cuts[['Tier 2']] <- cut_tiers_tier_2 } else { warnings <- c(warnings, paste0('cut_invalid:', 'Tier 2')) }
if (!is.null(cut_tiers_tier_3) && is.logical(cut_tiers_tier_3)) { cuts[['Tier 3']] <- cut_tiers_tier_3 } else { warnings <- c(warnings, paste0('cut_invalid:', 'Tier 3')) }
if (!is.null(cut_tiers_tier_4) && is.logical(cut_tiers_tier_4)) { cuts[['Tier 4']] <- cut_tiers_tier_4 } else { warnings <- c(warnings, paste0('cut_invalid:', 'Tier 4')) }
if (!is.null(cut_segments_segment_a) && is.logical(cut_segments_segment_a)) { cuts[['Segment A']] <- cut_segments_segment_a } else { warnings <- c(warnings, paste0('cut_invalid:', 'Segment A')) }
if (!is.null(cut_segments_segment_b) && is.logical(cut_segments_segment_b)) { cuts[['Segment B']] <- cut_segments_segment_b } else { warnings <- c(warnings, paste0('cut_invalid:', 'Segment B')) }
if (!is.null(cut_segments_segment_c) && is.logical(cut_segments_segment_c)) { cuts[['Segment C']] <- cut_segments_segment_c } else { warnings <- c(warnings, paste0('cut_invalid:', 'Segment C')) }
if (!is.null(cut_segments_segment_d) && is.logical(cut_segments_segment_d)) { cuts[['Segment D']] <- cut_segments_segment_d } else { warnings <- c(warnings, paste0('cut_invalid:', 'Segment D')) }
if (!is.null(cut_priority_accounts_priority_account) && is.logical(cut_priority_accounts_priority_account)) { cuts[['Priority Account']] <- cut_priority_accounts_priority_account } else { warnings <- c(warnings, paste0('cut_invalid:', 'Priority Account')) }
if (!is.null(cut_priority_accounts_non_priority_account) && is.logical(cut_priority_accounts_non_priority_account)) { cuts[['Non-Priority Account']] <- cut_priority_accounts_non_priority_account } else { warnings <- c(warnings, paste0('cut_invalid:', 'Non-Priority Account')) }
if (!is.null(cut_total_total) && is.logical(cut_total_total)) { cuts[['Total']] <- cut_total_total } else { warnings <- c(warnings, paste0('cut_invalid:', 'Total')) }

preflight_cuts <- lapply(names(cuts), function(nm) list(name = nm, valid = TRUE, error = NA))

dir.create('temp-outputs/output-2025-08-08T22-06-58-209Z/results', recursive = TRUE, showWarnings = FALSE)
write_table <- function(data, var_name, levels_df, table_id) {
  v <- tryCatch({ data[[var_name]] }, error = function(e) { warnings <<- c(warnings, paste0('var:', var_name, ':', e$message)); return(NULL) })
  if (is.null(v)) { return(invisible(NULL)) }
  if (!is.null(levels_df)) {
    v <- factor(v, levels = levels_df$value, labels = levels_df$label)
  }
  count_list <- lapply(cuts, function(idx) {
    tab <- table(v[idx], useNA = 'no')
    if (is.factor(v)) {
      lv <- levels(v)
      res <- as.integer(tab[lv])
      res[is.na(res)] <- 0
      res
    } else {
      as.integer(tab)
    }
  })
  counts <- do.call(cbind, count_list)
  colnames(counts) <- names(cuts)
  rn <- if (is.factor(v)) levels(v) else rownames(table(v))
  rownames(counts) <- rn
  col_totals <- colSums(counts)
  denom <- ifelse(col_totals == 0, 1, col_totals)
  perc <- sweep(counts, 2, denom, "/") * 100
  out <- data.frame(Level = rownames(counts), counts, perc, check.names = FALSE)
  write.csv(out, sprintf('temp-outputs/output-2025-08-08T22-06-58-209Z/results/%s.csv', table_id), row.names = FALSE)
}

preflight_vars <- list()
ok <- tryCatch({ data[['status']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'status', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='status', valid=ok)))
if (ok) write_table(data, 'status', data.frame(value=c(1,2,3,4), label=c('Terminated','Overquota','Qualified','Partial')), 'status')
ok <- tryCatch({ data[['S1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S1', valid=ok)))
if (ok) write_table(data, 'S1', data.frame(value=c(1,2,3), label=c('I would like to proceed and protect my identity','I would like to proceed and give permission for my contact details to be passed on to the Drug Safety department of the company if an adverse event is mentioned by me during the survey','I don�t want to proceed')), 's1')
ok <- tryCatch({ data[['S2b']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S2b', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S2b', valid=ok)))
if (ok) write_table(data, 'S2b', data.frame(value=c(1,2,3,99), label=c('Physician','Nurse Practitioner','Physician�s Assistant','Other')), 's2b')
ok <- tryCatch({ data[['S2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S2', valid=ok)))
if (ok) write_table(data, 'S2', data.frame(value=c(1,2,3,4,5,6,7,99), label=c('Cardiologist','Internal Medicine / General Practitioner / Primary Care / Family Practice','Nephrologist','Endocrinologist','Lipidologist','Nurse Practitioner','Physician�s Assistant','Other')), 's2')
ok <- tryCatch({ data[['S2a']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S2a', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S2a', valid=ok)))
if (ok) write_table(data, 'S2a', data.frame(value=c(1,2,3), label=c('Cardiologist','Internal Medicine / General Practitioner / Primary Care / Family Practice','Other')), 's2a')
ok <- tryCatch({ data[['qCARD_SPECIALTY']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'qCARD_SPECIALTY', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='qCARD_SPECIALTY', valid=ok)))
if (ok) write_table(data, 'qCARD_SPECIALTY', data.frame(value=c(1,2), label=c('CARD','NEPH/ENDO/LIP')), 'qcard-specialty')
ok <- tryCatch({ data[['qSPECIALTY']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'qSPECIALTY', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='qSPECIALTY', valid=ok)))
if (ok) write_table(data, 'qSPECIALTY', data.frame(value=c(1,2,3), label=c('CARD','PCP','NPPA')), 'qspecialty')
ok <- tryCatch({ data[['S3a']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S3a', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S3a', valid=ok)))
if (ok) write_table(data, 'S3a', data.frame(value=c(1,2,3), label=c('Interventional Cardiologist','General Cardiologist','Preventative Cardiologist')), 's3a')
ok <- tryCatch({ data[['qTYPE_OF_CARD']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'qTYPE_OF_CARD', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='qTYPE_OF_CARD', valid=ok)))
if (ok) write_table(data, 'qTYPE_OF_CARD', data.frame(value=c(1,2,3), label=c('Interventional Card','General Card','Preventative Card')), 'qtype-of-card')
ok <- tryCatch({ data[['qON_LIST_OFF_LIST']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'qON_LIST_OFF_LIST', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='qON_LIST_OFF_LIST', valid=ok)))
if (ok) write_table(data, 'qON_LIST_OFF_LIST', data.frame(value=c(1,2,3,4,5,6), label=c('CARD ON-LIST','CARD OFF-LIST','PCP ON-LIST','PCP OFF-LIST','NPPA ON-LIST','NPPA OFF-LIST')), 'qon-list-off-list')
ok <- tryCatch({ data[['qLIST_TIER']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'qLIST_TIER', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='qLIST_TIER', valid=ok)))
if (ok) write_table(data, 'qLIST_TIER', data.frame(value=c(1,2,3,4), label=c('TIER 1','TIER 2','TIER 3','TIER 4')), 'qlist-tier')
ok <- tryCatch({ data[['qLIST_PRIORITY_ACCOUNT']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'qLIST_PRIORITY_ACCOUNT', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='qLIST_PRIORITY_ACCOUNT', valid=ok)))
if (ok) write_table(data, 'qLIST_PRIORITY_ACCOUNT', data.frame(value=c(1,2), label=c('PRIORITY','NOT PRIORITY')), 'qlist-priority-account')
ok <- tryCatch({ data[['S4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S4', valid=ok)))
if (ok) write_table(data, 'S4', data.frame(value=c(1,2,3), label=c('Board Eligible','Board Certified','Neither')), 's4')
ok <- tryCatch({ data[['S7']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S7', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S7', valid=ok)))
if (ok) write_table(data, 'S7', data.frame(value=c(1,2), label=c('Full-Time','Part-Time')), 's7')
ok <- tryCatch({ data[['S9']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S9', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S9', valid=ok)))
if (ok) write_table(data, 'S9', data.frame(value=c(1,2,3,4,5,6,7,8), label=c('Private Solo Practice','Private Group Practice','Multi-specialty Practice / Comprehensive Care','Staff HMO','Community Hospital','Academic/University Hospital','VA Hospital','None of the above')), 's9')
ok <- tryCatch({ data[['A2a']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A2a', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A2a', valid=ok)))
if (ok) write_table(data, 'A2a', data.frame(value=c(1,2,3), label=c('Recommend a non-statin lipid-lowering agent for patients on maximally tolerated statins with LDL-C levels ?55 mg/dL','Recommend a non-statin lipid-lowering agent for patients on maximally tolerated statins with LDL-C levels ?70 mg/dL','Recommend a non-statin lipid-lowering agent for patients on maximally tolerated statins with LDL-C levels ?100 mg/dL')), 'a2a')
ok <- tryCatch({ data[['A2b']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A2b', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A2b', valid=ok)))
if (ok) write_table(data, 'A2b', data.frame(value=c(1,2,3), label=c('Recommend a statin first','Recommend a statin + ezetimibe first','Recommend a PCSK9i first')), 'a2b')
ok <- tryCatch({ data[['A5']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A5', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A5', valid=ok)))
if (ok) write_table(data, 'A5', data.frame(value=c(1,2,3,4), label=c('Within 3 months','4-6 months','7-12 months','Over a year')), 'a5')
ok <- tryCatch({ data[['Region']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'Region', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='Region', valid=ok)))
if (ok) write_table(data, 'Region', data.frame(value=c(1,2,3,4,5,6), label=c('Northeast','South','Midwest','West','Other','Invalid Region')), 'region')
ok <- tryCatch({ data[['B3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'B3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='B3', valid=ok)))
if (ok) write_table(data, 'B3', data.frame(value=c(1,2,3), label=c('Urban','Suburban','Rural')), 'b3')
ok <- tryCatch({ data[['QCONSENT']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'QCONSENT', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='QCONSENT', valid=ok)))
if (ok) write_table(data, 'QCONSENT', data.frame(value=c(1,2), label=c('Yes','No')), 'qconsent')
ok <- tryCatch({ data[['S5r1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r1', valid=ok)))
if (ok) write_table(data, 'S5r1', data.frame(value=c(0,1), label=c('0','1')), 's5r1')
ok <- tryCatch({ data[['S5r2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r2', valid=ok)))
if (ok) write_table(data, 'S5r2', data.frame(value=c(0,1), label=c('0','1')), 's5r2')
ok <- tryCatch({ data[['S5r3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r3', valid=ok)))
if (ok) write_table(data, 'S5r3', data.frame(value=c(0,1), label=c('0','1')), 's5r3')
ok <- tryCatch({ data[['S5r4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r4', valid=ok)))
if (ok) write_table(data, 'S5r4', data.frame(value=c(0,1), label=c('0','1')), 's5r4')
ok <- tryCatch({ data[['S5r5']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r5', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r5', valid=ok)))
if (ok) write_table(data, 'S5r5', data.frame(value=c(0,1), label=c('0','1')), 's5r5')
ok <- tryCatch({ data[['S5r6']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r6', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r6', valid=ok)))
if (ok) write_table(data, 'S5r6', data.frame(value=c(0,1), label=c('0','1')), 's5r6')
ok <- tryCatch({ data[['S5r7']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'S5r7', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='S5r7', valid=ok)))
if (ok) write_table(data, 'S5r7', data.frame(value=c(0,1), label=c('0','1')), 's5r7')
ok <- tryCatch({ data[['A1r1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A1r1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A1r1', valid=ok)))
if (ok) write_table(data, 'A1r1', data.frame(value=c(1,2), label=c('1','2')), 'a1r1')
ok <- tryCatch({ data[['A1r2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A1r2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A1r2', valid=ok)))
if (ok) write_table(data, 'A1r2', data.frame(value=c(1,2), label=c('1','2')), 'a1r2')
ok <- tryCatch({ data[['A1r3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A1r3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A1r3', valid=ok)))
if (ok) write_table(data, 'A1r3', data.frame(value=c(1,2), label=c('1','2')), 'a1r3')
ok <- tryCatch({ data[['A1r4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A1r4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A1r4', valid=ok)))
if (ok) write_table(data, 'A1r4', data.frame(value=c(1,2), label=c('1','2')), 'a1r4')
ok <- tryCatch({ data[['A6r1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r1', valid=ok)))
if (ok) write_table(data, 'A6r1', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r1')
ok <- tryCatch({ data[['A6r2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r2', valid=ok)))
if (ok) write_table(data, 'A6r2', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r2')
ok <- tryCatch({ data[['A6r3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r3', valid=ok)))
if (ok) write_table(data, 'A6r3', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r3')
ok <- tryCatch({ data[['A6r4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r4', valid=ok)))
if (ok) write_table(data, 'A6r4', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r4')
ok <- tryCatch({ data[['A6r5']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r5', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r5', valid=ok)))
if (ok) write_table(data, 'A6r5', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r5')
ok <- tryCatch({ data[['A6r6']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r6', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r6', valid=ok)))
if (ok) write_table(data, 'A6r6', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r6')
ok <- tryCatch({ data[['A6r7']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r7', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r7', valid=ok)))
if (ok) write_table(data, 'A6r7', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r7')
ok <- tryCatch({ data[['A6r8']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A6r8', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A6r8', valid=ok)))
if (ok) write_table(data, 'A6r8', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a6r8')
ok <- tryCatch({ data[['A7r1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A7r1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A7r1', valid=ok)))
if (ok) write_table(data, 'A7r1', data.frame(value=c(0,1), label=c('0','1')), 'a7r1')
ok <- tryCatch({ data[['A7r2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A7r2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A7r2', valid=ok)))
if (ok) write_table(data, 'A7r2', data.frame(value=c(0,1), label=c('0','1')), 'a7r2')
ok <- tryCatch({ data[['A7r3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A7r3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A7r3', valid=ok)))
if (ok) write_table(data, 'A7r3', data.frame(value=c(0,1), label=c('0','1')), 'a7r3')
ok <- tryCatch({ data[['A7r4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A7r4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A7r4', valid=ok)))
if (ok) write_table(data, 'A7r4', data.frame(value=c(0,1), label=c('0','1')), 'a7r4')
ok <- tryCatch({ data[['A7r5']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A7r5', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A7r5', valid=ok)))
if (ok) write_table(data, 'A7r5', data.frame(value=c(0,1), label=c('0','1')), 'a7r5')
ok <- tryCatch({ data[['A8r1c1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r1c1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r1c1', valid=ok)))
if (ok) write_table(data, 'A8r1c1', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r1c1')
ok <- tryCatch({ data[['A8r1c2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r1c2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r1c2', valid=ok)))
if (ok) write_table(data, 'A8r1c2', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r1c2')
ok <- tryCatch({ data[['A8r1c3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r1c3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r1c3', valid=ok)))
if (ok) write_table(data, 'A8r1c3', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r1c3')
ok <- tryCatch({ data[['A8r2c1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r2c1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r2c1', valid=ok)))
if (ok) write_table(data, 'A8r2c1', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r2c1')
ok <- tryCatch({ data[['A8r2c2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r2c2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r2c2', valid=ok)))
if (ok) write_table(data, 'A8r2c2', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r2c2')
ok <- tryCatch({ data[['A8r2c3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r2c3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r2c3', valid=ok)))
if (ok) write_table(data, 'A8r2c3', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r2c3')
ok <- tryCatch({ data[['A8r3c1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r3c1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r3c1', valid=ok)))
if (ok) write_table(data, 'A8r3c1', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r3c1')
ok <- tryCatch({ data[['A8r3c2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r3c2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r3c2', valid=ok)))
if (ok) write_table(data, 'A8r3c2', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r3c2')
ok <- tryCatch({ data[['A8r3c3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r3c3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r3c3', valid=ok)))
if (ok) write_table(data, 'A8r3c3', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r3c3')
ok <- tryCatch({ data[['A8r4c1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r4c1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r4c1', valid=ok)))
if (ok) write_table(data, 'A8r4c1', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r4c1')
ok <- tryCatch({ data[['A8r4c2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r4c2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r4c2', valid=ok)))
if (ok) write_table(data, 'A8r4c2', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r4c2')
ok <- tryCatch({ data[['A8r4c3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r4c3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r4c3', valid=ok)))
if (ok) write_table(data, 'A8r4c3', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r4c3')
ok <- tryCatch({ data[['A8r5c1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r5c1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r5c1', valid=ok)))
if (ok) write_table(data, 'A8r5c1', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r5c1')
ok <- tryCatch({ data[['A8r5c2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r5c2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r5c2', valid=ok)))
if (ok) write_table(data, 'A8r5c2', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r5c2')
ok <- tryCatch({ data[['A8r5c3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A8r5c3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A8r5c3', valid=ok)))
if (ok) write_table(data, 'A8r5c3', data.frame(value=c(1,2,3,4,5), label=c('1','2','3','4','5')), 'a8r5c3')
ok <- tryCatch({ data[['A9c1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A9c1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A9c1', valid=ok)))
if (ok) write_table(data, 'A9c1', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a9c1')
ok <- tryCatch({ data[['A9c2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A9c2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A9c2', valid=ok)))
if (ok) write_table(data, 'A9c2', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a9c2')
ok <- tryCatch({ data[['A9c3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A9c3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A9c3', valid=ok)))
if (ok) write_table(data, 'A9c3', data.frame(value=c(1,2,3,4), label=c('1','2','3','4')), 'a9c3')
ok <- tryCatch({ data[['A10r1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A10r1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A10r1', valid=ok)))
if (ok) write_table(data, 'A10r1', data.frame(value=c(0,1), label=c('0','1')), 'a10r1')
ok <- tryCatch({ data[['A10r2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A10r2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A10r2', valid=ok)))
if (ok) write_table(data, 'A10r2', data.frame(value=c(0,1), label=c('0','1')), 'a10r2')
ok <- tryCatch({ data[['A10r3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A10r3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A10r3', valid=ok)))
if (ok) write_table(data, 'A10r3', data.frame(value=c(0,1), label=c('0','1')), 'a10r3')
ok <- tryCatch({ data[['A10r4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A10r4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A10r4', valid=ok)))
if (ok) write_table(data, 'A10r4', data.frame(value=c(0,1), label=c('0','1')), 'a10r4')
ok <- tryCatch({ data[['A10r5']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A10r5', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A10r5', valid=ok)))
if (ok) write_table(data, 'A10r5', data.frame(value=c(0,1), label=c('0','1')), 'a10r5')
ok <- tryCatch({ data[['A10r6']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'A10r6', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='A10r6', valid=ok)))
if (ok) write_table(data, 'A10r6', data.frame(value=c(0,1), label=c('0','1')), 'a10r6')
ok <- tryCatch({ data[['B5r1']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'B5r1', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='B5r1', valid=ok)))
if (ok) write_table(data, 'B5r1', data.frame(value=c(0,1), label=c('0','1')), 'b5r1')
ok <- tryCatch({ data[['B5r2']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'B5r2', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='B5r2', valid=ok)))
if (ok) write_table(data, 'B5r2', data.frame(value=c(0,1), label=c('0','1')), 'b5r2')
ok <- tryCatch({ data[['B5r3']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'B5r3', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='B5r3', valid=ok)))
if (ok) write_table(data, 'B5r3', data.frame(value=c(0,1), label=c('0','1')), 'b5r3')
ok <- tryCatch({ data[['B5r4']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'B5r4', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='B5r4', valid=ok)))
if (ok) write_table(data, 'B5r4', data.frame(value=c(0,1), label=c('0','1')), 'b5r4')
ok <- tryCatch({ data[['B5r5']]; TRUE }, error = function(e) { warnings <<- c(warnings, paste0('var:', 'B5r5', ':', e$message)); FALSE })
preflight_vars <- append(preflight_vars, list(list(var='B5r5', valid=ok)))
if (ok) write_table(data, 'B5r5', data.frame(value=c(0,1), label=c('0','1')), 'b5r5')
preflight <- list(cuts = preflight_cuts, vars = preflight_vars, warnings = warnings)
write_json(preflight, 'temp-outputs/output-2025-08-08T22-06-58-209Z/r/preflight.json', auto_unbox = TRUE, pretty = TRUE)
